#!/usr/bin/env bash

stack build --profile

stack exec --profile -- mcmc-date \
      --analysisName test \
      --rootedTree data/time.tree \
      --trees data/alignment.fasta.trees.only \
      --calibrations data/calibrations.csv \
      --computeMarginalLikelihood \
      +RTS -p -h -s

hp2ps mcmc-date.hp
