#!/usr/bin/env bash

stack exec -- mcmc-date prepare \
      --analysis-name profile \
      --rooted-tree data/time.tree \
      --in-trees data/alignment.fasta.trees.only

stack exec --profile -- mcmc-date run \
      --analysis-name profile \
      --calibrations data/calibrations.csv \
      +RTS -p -h -s

hp2ps mcmc-date.hp
