#!/usr/bin/env bash

set -e

analysis_name="test"
rooted_tree="data/time.tree"
trees="data/alignment.fasta.trees.only"
calibrations="data/calibrations.csv"
constraints="data/constraints.csv"
profile=""

../../scripts/run \
    "$analysis_name" \
    "$rooted_tree" \
    "$trees" \
    "$calibrations" \
    "$constraints" \
    "$profile" \
    "$1"
