#!/usr/bin/env bash

set -e

analysis_name="test-06-leaves"
rooted_tree="data/time.tree"
trees="data/test.treelist"
calibrations=""
# calibrations="data/calibrations.csv"
constraints=""
profile=""

../../scripts/run \
    "$analysis_name" \
    "$rooted_tree" \
    "$trees" \
    "$calibrations" \
    "$constraints" \
    "$profile" \
    "$1"
