#!/usr/bin/env bash

# Analyze all results.

set -e

usage() {
  echo "Usage: $(basename "$0") [options]"
  echo
  echo "Options:"
  echo " -h  Display help and exit"
  echo " -s  Skip files with previous analysis"
}

skip=FALSE
while getopts "sh" o; do
  case "$o" in
    s) skip=TRUE
       ;;
    h) usage
       exit 0
       ;;
    *) usage
       exit 1
       ;;
  esac
done

function analyze_tree_monitor() {
    echo "Prepare the Nexus file to be opened with Densitree."
    echo "Thin the monitor file."
    trace-thin 5 "$1" > "${1}.thinned"
    echo "Convert thinned file to Nexus format."
    trees-monitor-to-nexus "${1}.thinned"

    echo "Compute other summary statistics."
    if [[ "$1" == *"timetree"* ]]; then
      trees-monitor-summary-ultrametric "${1}" 0.25
    else
      trees-monitor-summary "${1}" 0.25
    fi
}

shopt -s extglob

if [[ -n $1 ]]
then
  ds=("$1")
else
  ds=(results*)
fi

for d in "${ds[@]}"
do
    ( cd "$d"
      echo "Current directory: ${PWD}."
      for m in *{timetree,ratetree}.@(00.|)monitor
      do
        if [[ "$skip" = "TRUE" ]] && [[ -e "${m}.thinned" ]]; then
          echo "Skip analysis of ${m}."
        else
          echo "Analyze monitor file ${m}."
          analyze_tree_monitor "$m"
        fi
      done
      echo "Create tree file with node indices."
      for f in *.meantree
      do
          tree-identify "$f"
      done
    )
done
